---
# tasks file for node-exporter role
# This role installs and configures Prometheus node-exporter on target servers.

# Download the latest node-exporter binary from official Prometheus GitHub release
- name: Download node-exporter binary
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'

# Extract the downloaded archive and place the binary in /usr/local/bin
- name: Extract node-exporter binary
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /usr/local/bin
    remote_src: true
    extra_opts: [--strip-components=1]

# Create a dedicated system user to run node-exporter securely
- name: Create node-exporter user
  ansible.builtin.user:
    name: node_exporter
    system: true
    shell: /bin/false

# Set proper ownership and permissions for the node-exporter binary
- name: Set ownership on node_exporter binary
  ansible.builtin.file:
    path: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: '0755'

# Start node-exporter manually since systemd is not available in containers
- name: Start node-exporter manually in background (without systemd)
  become: true
  shell: |
    nohup /usr/local/bin/node_exporter > /var/log/node_exporter.log 2>&1 &
  args:
    executable: /bin/bash