---
# tasks file for node-exporter role
# This role installs and configures Prometheus node-exporter on target servers.

# Download the latest node-exporter binary from official Prometheus GitHub release
- name: Download node-exporter binary
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

# Extract the downloaded archive and place the binary in /usr/local/bin
- name: Extract node-exporter binary
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: [--strip-components=1]

# Create a dedicated system user to run node-exporter securely
- name: Create node-exporter user
  user:
    name: node_exporter
    system: yes
    shell: /bin/false

# Set proper ownership and permissions for the node-exporter binary
- name: Set ownership on node_exporter binary
  file:
    path: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: '0755'

# Create a systemd service unit file for managing node-exporter service
- name: Create systemd service file for node-exporter
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=default.target

# Ensure node-exporter service is enabled (start on boot) and running now
- name: Enable and start node-exporter service
  systemd:
    name: node_exporter
    enabled: true
    state: started
    daemon_reload: true
