---
# tasks file for grafana role
# Installs Grafana and sets up Prometheus datasource and dashboards

# Install required packages for adding external APT repositories
- name: Install packages for Grafana
  apt:
    name:
      - apt-transport-https         # Enables APT over HTTPS
      - software-properties-common  # Tools for managing APT repositories
      - wget                        # Required for downloading files
    state: present
    update_cache: yes
  become: true   # Run with elevated privileges (sudo)

# Add Grafana's official GPG key for APT package verification
- name: Add Grafana APT key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

# Add Grafana's APT repository to the system sources list
- name: Add Grafana APT repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

# Install Grafana from the newly added repository
- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

# Enable and start the Grafana systemd service
- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    enabled: true     # Start at boot
    state: started    # Start now
    daemon_reload: true  # Reload systemd to recognize the new service

# Create a separate datasource file for each Prometheus instance
- name: Provision multiple Prometheus datasources
  template:
    src: prometheus-datasource.yml.j2
    dest: "/etc/grafana/provisioning/datasources/{{ item.name }}.yml"
    owner: root
    group: grafana
    mode: '0644'
  loop: "{{ prometheus_targets }}"
